name: Run Torch Quantizers Compatibility Tests

on:
  workflow_call:
    inputs:
      save_version:
        description: 'MCT Quantizers version to save models'
        required: true
        type: string
      python_version:
        description: 'Python version'
        required: true
        type: string
        default: '3.10.*'
      torch_version:
        description: 'Torch version'
        required: true
        type: string
        default: '2.0.*'

jobs:
  run-torch-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Python 3
        uses: actions/setup-python@v5
        with:
          python-version: ${{  inputs.python_version  }}
      - name: Modify requirements for Torch 2.2
        if: startsWith(inputs.torch_version, '2.2')
        run: |
          grep -v 'numpy' requirements.txt > temp_requirements.txt
          echo "numpy<2" >> temp_requirements.txt
          mv temp_requirements.txt requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install torch==${{  inputs.torch_version  }} onnx onnxruntime "onnxruntime-extensions<0.14"
      - name: Checkout to MCT Quantizers requested tag for saving test models
        run: |
          git checkout tags/${{  inputs.save_version  }}
      - name: Run save model tests
        run: |
          cd tests
          echo "Current directory: $PWD"
          export PYTHONPATH="$PWD:${PYTHONPATH}"
          echo "Updated PYTHONPATH: $PYTHONPATH"
          cd ..
          python tests/compatibility_tests/torch_comp_tests/compatibility_weights_save_model_test_suite.py ${{  inputs.save_version  }}
          python tests/compatibility_tests/torch_comp_tests/compatibility_activation_save_model_test_suite.py ${{  inputs.save_version  }}
      - name: Checkout to MCT Quantizers latest version
        run: |
          git checkout main
      - name: Run load model tests with latest version
        run: |
          cd tests
          echo "Current directory: $PWD"
          export PYTHONPATH="$PWD:${PYTHONPATH}"
          echo "Updated PYTHONPATH: $PYTHONPATH"
          cd ..
          python tests/compatibility_tests/torch_comp_tests/compatibility_weights_load_model_test_suite.py ${{  inputs.save_version  }}
          python tests/compatibility_tests/torch_comp_tests/compatibility_activation_load_model_test_suite.py ${{  inputs.save_version  }}
