name: Test pip install
on:
  workflow_dispatch: # Allow manual triggers
    inputs:
      mct_quantizers_version:
        description: 'MCT Quantizers version'
        required: true
        default: 'v1.1.0'
      python_version:
        description: 'Python version'
        required: false
        default: '3.10'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: ${{  inputs.python_version  }}
      - name: Install dependencies
        run: |
          git checkout tags/${{  inputs.mct_quantizers_version  }}
          pip install -r requirements.txt
      - name: Build WHL file
        run: |
          version=$(python -c 'import mct_quantizers; print(mct_quantizers.__version__)')
          now=$(date +'%Y%m%d-%H%M%S')
          echo "nightly_version=$version.$now" >> $GITHUB_ENV
          sed -i "s/attr: mct_quantizers.__version__/$version.$now/g" setup.cfg
          sed -i "s/name='mct_quantizers'/name='mct-quantizers'/g" setup.py
          python setup.py sdist bdist_wheel
      - name: Install WHL file
        run: |
          whl_file=$(find . -iname "*.whl")
          echo $whl_file
          pip install $whl_file
          pip list
          python -c 'import mct_quantizers; print(mct_quantizers.__version__)'
      - name: Remove MCT Quantizers code
        run: |
          rm -rf mct_quantizers
      - name: Install TF
        run: |
          pip install tensorflow==2.13.*
      - name: Run TF Tests
        run: |
          python -m unittest discover tests/keras_tests --verbose
      - name: Prepare for Torch
        run: |
          pip uninstall tensorflow
          pip install torch==2.0.* torchvision onnx onnxruntime onnxruntime-extensions
      - name: Run Torch Tests
        run: |
          python -m unittest discover tests/pytorch_tests --verbose
          
