name: Run Backward Compatibility Test - Tensorflow 2.14 MCTQ v1.3.0
on:
  workflow_dispatch: # Allow manual triggers
  schedule:
    - cron: 0 0 * * *

jobs:
  run-comp-tensorflow-2_13-v1_3:
    uses: ./.github/workflows/compatibility_keras_tests.yml
    with:
      save_version: "v1.3.0"
      python_version: "3.10"
      tf_version: "2.14"
