name: Run Backward Compatibility Test - Pytorch 2.1 MCTQ v1.4.0
on:
  workflow_dispatch: # Allow manual triggers
  schedule:
    - cron: 0 0 * * *

jobs:
  run-comp-torch-2_1-v1_4:
    uses: ./.github/workflows/compatibility_torch_tests.yml
    with:
      save_version: "v1.4.0"
      python_version: "3.10"
      torch_version: "2.1.*"
